const seoConfig = [
  { pageName: "home", title: "Home - Ratan Decor", description: "Welcome to Ratan Decor, your one-stop shop for premium home decor.", keywords: "home, ratan decor, home decor" },
  { pageName: "products", title: "Products - Ratan Decor", description: "Browse our exclusive collection of home decor products.", keywords: "products, shopping, home decor" },
  { pageName: "productdetails", title: "Product Details - Ratan Decor", description: "View detailed information about our home decor products.", keywords: "product, details, home decor" },
  { pageName: "cart", title: "Your Cart - Ratan Decor", description: "Review items in your shopping cart.", keywords: "cart, checkout, shopping" },
  { pageName: "checkout", title: "Checkout - Ratan Decor", description: "Complete your purchase securely.", keywords: "checkout, payment, shopping" },
  { pageName: "order-success", title: "Order Success - Ratan Decor", description: "Thank you for your order! It has been placed successfully.", keywords: "order, success, purchase" },
  { pageName: "about", title: "About Us - Ratan Decor", description: "Learn about Ratan Decor and our mission.", keywords: "about, company, home decor" },
  { pageName: "contact", title: "Contact Us - Ratan Decor", description: "Get in touch with our support team.", keywords: "contact, support, customer service" },
  { pageName: "privacy", title: "Privacy Policy - Ratan Decor", description: "Understand our privacy practices.", keywords: "privacy, policy, data protection" },
  { pageName: "terms", title: "Terms & Conditions - Ratan Decor", description: "Read our terms and conditions.", keywords: "terms, conditions, legal" },
  { pageName: "cookiespolicy", title: "Cookies Policy - Ratan Decor", description: "Learn how we use cookies.", keywords: "cookies, policy, website" },
  { pageName: "returns", title: "Returns & Refunds - Ratan Decor", description: "Understand our return and refund policy.", keywords: "returns, refunds, policy" },
  { pageName: "disclaimer", title: "Disclaimer - Ratan Decor", description: "Read our legal disclaimer.", keywords: "disclaimer, legal, terms" },
  { pageName: "faq", title: "FAQ - Ratan Decor", description: "Find answers to frequently asked questions.", keywords: "faq, help, support" },
  { pageName: "profile", title: "Profile - Ratan Decor", description: "Manage your account settings.", keywords: "profile, account, user" },
];